# The following bytes have significant meaning in JSON
const BACKSPACE      = @compat UInt8('\b')
const TAB            = @compat UInt8('\t')
const NEWLINE        = @compat UInt8('\n')
const FORM_FEED      = @compat UInt8('\f')
const RETURN         = @compat UInt8('\r')
const SPACE          = @compat UInt8(' ')
const STRING_DELIM   = @compat UInt8('"')
const PLUS_SIGN      = @compat UInt8('+')
const DELIMITER      = @compat UInt8(',')
const MINUS_SIGN     = @compat UInt8('-')
const DECIMAL_POINT  = @compat UInt8('.')
const SOLIDUS        = @compat UInt8('/')
const DIGIT_ZERO     = @compat UInt8('0')
const DIGIT_NINE     = @compat UInt8('9')
const SEPARATOR      = @compat UInt8(':')
const LATIN_UPPER_A  = @compat UInt8('A')
const LATIN_UPPER_E  = @compat UInt8('E')
const LATIN_UPPER_F  = @compat UInt8('F')
const ARRAY_BEGIN    = @compat UInt8('[')
const BACKSLASH      = @compat UInt8('\\')
const ARRAY_END      = @compat UInt8(']')
const LATIN_A        = @compat UInt8('a')
const LATIN_B        = @compat UInt8('b')
const LATIN_E        = @compat UInt8('e')
const LATIN_F        = @compat UInt8('f')
const LATIN_L        = @compat UInt8('l')
const LATIN_N        = @compat UInt8('n')
const LATIN_R        = @compat UInt8('r')
const LATIN_S        = @compat UInt8('s')
const LATIN_T        = @compat UInt8('t')
const LATIN_U        = @compat UInt8('u')
const OBJECT_BEGIN   = @compat UInt8('{')
const OBJECT_END     = @compat UInt8('}')

const ESCAPES = @compat(Dict(
    STRING_DELIM => STRING_DELIM,
    BACKSLASH    => BACKSLASH,
    SOLIDUS      => SOLIDUS,
    LATIN_B      => BACKSPACE,
    LATIN_F      => FORM_FEED,
    LATIN_N      => NEWLINE,
    LATIN_R      => RETURN,
    LATIN_T      => TAB))
